[package]
name = "rusty"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.44.0", features = ["full"] }
tower = "0.5.2"
